name: Build
on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - run: npm install
            - run: npm run build
